name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: pip
        run: pip install pytest
      - name: start testing
        run: python -c "import sys; print(sys.version)"
