name: ci
on: [push]
jobs:
    test_project:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: pip install -r site/requirements.txt
